export const folders = [
    'configs',
    'enums',
    'controllers',
    'interfaces',
    'middlewares',
    'databases',
    'repositories',
    'routes',
    'services',
    'utils',
    'types',
    'validations',
];

export const folderMap: Record<string, string> = {
    controller: 'controllers',
    service: 'services',
    route: 'routes',
    repository: 'repositories',
    validation: 'validations',
    model: 'databases/models',
    interface: 'interfaces',
    types: 'types',
    resources: 'resources',
    config: 'configs',
    middleware: 'middlewares',
    util: 'utils',
    enum: 'enums',
};
